#!/bin/bash
#
# This script imports csv files created by anime_seasons.py into a database.
#
# Variables:
#   DB_NAME: the name of the database to import into
#   TYPE: either hentai or anime. If hentai, then the hentai csv files are
#         used. If anime, then the anime csv files are used.
#   YEAR_BEG: the year to start importing from.  csv files with a year in
#             [YEAR_BEG, YEAR_END] will be imported.
#             than or equal to this variable will be imported.
#   YEAR_END: the year to stop importing at.  csv files with a year in
#             [YEAR_BEG, YEAR_END] will be imported.

HENTAI_DB="Hentai.db"
ANIME_DB="Sybil.db"
DB_NAME="Hentai.db"
TYPE="hentai"
YEAR_BEG=1980
YEAR_END=2016
GET_WINTER=0
GET_SPRING=0
GET_SUMMER=0
GET_FALL=0
HAS_SEASON_FLAG=0

show_help() {
    echo -e "\n\nUsage:\n"\
         "    ./import_csv_anime.sh <seasons> <years> <type>\n"\
         "Both year arguments, at least one season argument, and a type must"\
         "be given."
    echo -e '\n\nThis script imports csv files created by anime_seasons.py\n'\
         'into a database.  If the csv files are not generated by\n'\
         'anime_seasons.py, then generate them with the following format:\n'\
         'The csv file has eight fields separated by a } character.  The\n'\
         'meaning of each field is:\n'\
         '    field 1: name of the anime\n'\
         '    field 2: null\n'\
         '    field 3: number of episodes\n'\
         '    field 4: date aired as YYYY-MM-DD\n'\
         '    field 5: animation studio\n'\
         '    field 6: null\n'\
         '    field 7: null\n'\
         '    field 8: null\n\n'\
         'The csv files must be named <season><year>_<type>.csv, where\n'\
         '<season> is one of w, sp, su, and f, <year> is a four digit year,\n'\
         'and <type> is either anime or hentai.\n\n'
    echo -e '<years>\n'\
         '-b n  the year to begin importing from. n should be a 4 digit year.'\
         '-e n  the year to stop importing at. n should be a 4 digit year\n\n'
    echo -e '<seasons>\n'\
         '-w    import winter csv files.\n'\
         '-p    import spring csv files.\n'\
         '-s    import summer csv files.\n'\
         '-f    import fall csv files.\n\n'
    echo -e '<type>\n'\
         '-t c  the type of csv to import. The argument, c, should be a or h.\n'\
         '      If h, then the hentai csv files are used and imported into\n'\
         '      Hentai.db.  If a is passed, then the anime csv files are\n'\
         '      used and imported into Sybil.db.  If the database does not\n'\
         '      exist, then it is created.\n'
    echo '-h    show this help message.'
}

YEAR_REGEX="[0-9]{4}"

while getopts "wfspt:b:e:h" opt;
do
    case $opt in
        w)
            GET_WINTER=1
            HAS_SEASON_FLAG=1
            ;;
        p)
            GET_SPRING=1
            HAS_SEASON_FLAG=1
            ;;
        s)
            GET_SUMMER=1
            HAS_SEASON_FLAG=1
            ;;
        f)
            GET_FALL=1
            HAS_SEASON_FLAG=1
            ;;
        t)
            if [ "$OPTARG" == "a" ];
            then
                TYPE="anime"
                DB_NAME="$ANIME_DB"
            elif [ "$OPTARG" == "h" ];
            then
                TYPE="hentai"
                DB_NAME="$HENTAI_DB"
            else
                echo "-t argument must be a or h"
                exit
            fi
            ;;
            #TODO check if it's less than YEAR_END
        b)
            if [[ $OPTARG =~ $YEAR_REGEX ]];
            then
                YEAR_BEG=$OPTARG
            else
                echo "-b argument must be a 4-digit integer"
                exit
            fi
            ;;
        e)
            if [[ $OPTARG =~ $YEAR_REGEX ]];
            then
                YEAR_END=$OPTARG
            else
                echo "-b argument must be a 4-digit integer"
                exit
            fi
            ;;
        h)
            show_help
            exit
            ;;
    esac
done

if [ "$HAS_SEASON_FLAG" == 0 ];
then
    echo "Seasons not specified."\
         "At least one of -w, -p, -s, and -f must be given."
    exit
fi

if [ ! -f $DB_NAME ]
then
    SQL="CREATE TABLE 'Main' (id integer primary key, Name varchar(30), 'Episodes Watched'    unsigned smallint, 'Total Episodes' unsigned SmallInt, 'Date Aired' Date,            'Production Studio' varchar(30), Score unsigned Double(3,2), Genres varchar(100),    Notes varchar(256));"
    sqlite3 "$DB_NAME" "$SQL"
fi

sqlite3 $DB_NAME "CREATE TABLE 'Temp' (Name varchar(30), 'Episodes Watched' unsigned smallint, 'Total Episodes' unsigned SmallInt, 'Date Aired' Date, 'Production Studio' varchar(30), Score unsigned Double(3,2), Genres varchar(100), Notes varchar(256));"
for year in $(seq $YEAR_BEG $YEAR_END);
do
    if [ "$GET_WINTER" == 1 ];
    then
        sqlite3 $DB_NAME '.separator }' ".import w"$year"_"$TYPE".csv Temp"
    fi
    if [ "$GET_SPRING" == 1 ];
    then
        sqlite3 $DB_NAME '.separator }' ".import sp"$year"_"$TYPE".csv Temp"
    fi
    if [ "$GET_SUMMER" == 1 ];
    then
        sqlite3 $DB_NAME '.separator }' ".import su"$year"_"$TYPE".csv Temp"
    fi
    if [ "$GET_FALL" == 1 ];
    then
        sqlite3 $DB_NAME '.separator }' ".import f"$year"_"$TYPE".csv Temp"
    fi
done
sqlite3 $DB_NAME "insert into Main ('Name', 'Episodes Watched', 'Total Episodes', 'Date Aired', 'Production Studio', 'Score', 'Genres', 'Notes') select * from Temp;"
sqlite3 $DB_NAME 'DROP TABLE Temp;'
